print("-----------------------------------------")
print("ejercicio 4")
numero5=int(input("por favor ingrese el primer numero que de sea dividir:"))
numero6=int(input("por favor ingrese el segundo numero que de sea dividir:"))
ope3=numero5//numero6
print(("el reseultado de su operacion fue"),ope3 )
print("---------------------------------------------------------------------------------------")
print("ejercicio 5")
nombre=input("por favor ingrese su nombre:")
apellido=input("por favor ingrese su apellido:")
print(("bienvenido "),nombre , apellido)
print("---------------------------------------------------------------------------------------")
print("ejercicio 6")
nombre1=input("por favor ingrese su nombre:")
busqueda=nombre1[0]
print(("la primera letra de su nombre es"),busqueda)
print("---------------------------------------------------------------------------------------")
print("ejercicio 7")
nombre1=input("por favor ingrese su nombre:")
busqueda1=nombre1[-1]
print(("la ultima letra de su nombre es"),busqueda1)
print("---------------------------------------------------------------------------------------")
print("ejercicio 8")
nume1=int(input("por favor ingrese la base del rectrangulo:"))
nume2=int(input("por favor ingrese la altura del rectangulo:"))
opeo=nume1*nume2
print(("el resultado del area del rectangulo es"),opeo)
print("---------------------------------------------------------------------------------------")
print("ejercicio 9")
num1=int(input("por favor ingrese su año de nacimiento:"))
la=2025-num1
print(("su edad es"),la)
print("---------------------------------------------------------------------------------------")
print("ejercicio 10")
nombre=input("por favor ingrese su nombre:")
dominio=input("por favor ingrese su dominio:")
lil=nombre+"@"+dominio
print(("su correo es"),lil)
print("---------------------------------------------------------------------------------------")
print("ejercicio 11")
nombre3=input("por favor ingrese su nombre:")
print(len(nombre3))                 #el len se uriliza para saber cuantas letras tiene
print("---------------------------------------------------------------------------------------")
print("ejercicio 12")
con1=input("por favor ingrese una palabra:")
con2=input("por favor ingrese su segunda palabra:")
print("sus palabras convinadas fueron",con1,con2)
print("---------------------------------------------------------------------------------------")
print("ejercicio 13")
co1=input("por favor ingrese una palabra:")
pal=co1[1]
print("la seguna letra de su palabra fue",pal)
print("---------------------------------------------------------------------------------------")
print("ejercicio 14")
pi=input("por favor ingrese una palabra:")
pe=pi[0:3]
print("las tres letras de su plabra fuero",pe)
print("----------------------------------------------------------------------------------------")
print("ejercicio 15")
poo=input("por favor ingrese una palabra:")
puuu=poo[::-1]
print("la seguna letra de su palabra fue",puuu)
print("----------------------------------------------------------------------------------------")
print("ejercicio 16")
print("SUMA")
A=int(input("por favor ingrese el primer numero que de sea sumar:"))
B=int(input("por favor ingrese el segundo numero que de sea sumar:"))
AB=A+B
print(("el reseultado de su operacion fue"),AB)
print("RESTA")
C=int(input("por favor ingrese el primer numero que de sea restar:"))
D=int(input("por favor ingrese el segundo numero que de sea restar:"))
CD=C-D
print(("el reseultado de su operacion fue"),CD)
print("MULTIPLICACIÓN")
S=int(input("por favor ingrese el primer numero que de sea multiplicar:"))
D=int(input("por favor ingrese el segundo numero que de sea multiplicar:"))
SD=S*D
print(("el reseultado de su operacion fue"),SD )
print("DIVISION")
X=int(input("por favor ingrese el primer numero que de sea dividir:"))
K=int(input("por favor ingrese el segundo numero que de sea dividir:"))
XK=X//K
print(("el reseultado de su operacion fue"),XK)
print("----------------------------------------------------------------------------------------")
print("ejercicio 17")# print("----------------------------------------------------------------------------------")
print("taler")
prin("-------------------------------------------------------------------------------------")
print("pregunta 1")
numero1=int(input("por favor ingrese el primer numero que de sea sumar:"))
numero2=int(input("por favor ingrese el segundo numero que de sea sumar:"))
ope1=numero1+numero2
print(("el reseultado de su operacion fue"),ope1)
print("---------------------------------------------------------------------------------")
print("pregunta 2")
numero3=int(input("por favor ingrese el primer numero que de sea restar:"))
numero4=int(input("por favor ingrese el segundo numero que de sea restar:"))
ope2=numero3-numero4
print(("el reseultado de su operacion fue"),ope2 )
pint("---------------------------------------------------------------------------------------")
print("ejercicio 3")
numero7=int(input("por favor ingrese el primer numero que de sea multiplicar:"))
numero8=int(input("por favor ingrese el segundo numero que de sea multiplicar:"))
ope4=numero7*numero8
print(("el reseultado de su operacion fue"),ope4 )
pint("----------------------------------------------")
W=int(input("por favor ingrese un numero:"))
WD=W*2
print(("el reseultado de su operacion fue"),WD)
print("----------------------------------------------------------------------------------------")
print("ejercicio 18")
P=int(input("por favor ingrese un numero:"))
V=P//2
print(("el reseultado de su operacion fue"),V)
print("----------------------------------------------------------------------------------------")
print("ejercicio 19")
nombre78=input("por favor ingrese su frase:")
print(len(nombre78))     
print("----------------------------------------------------------------------------------------")
print("ejercicio 20")
pi = (input("por favor ingrese una palabra:"))
print("Repetida 3 veces: ", pi + " " + pi + " " + pi)
print("----------------------------------------------------------------------------------------")
print("ejercicio 21")
ko=(input("por favor ingrese una palabra:"))
print(ko[0:2],ko[3:])
print("----------------------------------------------------------------------------------------")
print("ejercicio 22")
polo=input("ingresa una palabra:")
print("la letra del medio de su palabra es",polo[2:3])
print("----------------------------------------------------------------------------------------")
print("ejercicio 23")
pel=input("ingresa una frase:")
print("los diez primeras palabras son ",pel[0:10])
print("----------------------------------------------------------------------------------------")
print("ejercicio 24")
result=int(("por favor ingrese un numero"))
print("su numero elevado al cuadrado fue",result*result)
print("----------------------------------------------------------------------------------------")
print("ejercicio 25")
resu=int(("por favor ingrese un numero"))
res=int(("por favor ingrese un numero"))
print("el numero mayor de estos dos es")